server:
  port: 8888

spring:
  application:
    name: usercard-manager

  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.zgmksscecprvpmjlraks
    password: '#^c%UbjyO6IniuB2'
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin

  logging:
    level:
      org:
        springframework:
          security: DEBUG


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

apiTitle: "Manager Service"
apiDescription: "Serviço de Gerenciamento do projeto Usercard manager"
apiVersion: "1.0.0"
apiContactName: "João Victor Barbosa"
apiContactEmail: "jvbaprof@gmail.com"